name: "코드 리뷰 체크리스트"
description: "PR 리뷰 시 확인 사항을 체크해주세요."
title: "[리뷰] 리뷰 대상 PR 제목을 적어주세요"
labels: ["review"]
body:
  - type: markdown
    attributes:
      value: |
        리뷰어님, 아래 항목들을 체크하고 의견을 남겨주세요.

  - type: checkboxes
    id: review-checklist
    attributes:
      label: 코드 리뷰 체크리스트
      options:
        - label: 코드가 이해하기 쉽게 작성되어 있나요?
        - label: 불필요한 코드나 주석은 없나요?
        - label: 디렉토리 및 파일 명명 규칙을 지켰나요?
        - label: 테스트 또는 실행 결과 확인했나요?
        - label: 개선이 필요한 부분에 대해 의견을 남겼나요?

  - type: textarea
    id: general-feedback
    attributes:
      label: 전반적인 피드백
      description: 좋았던 점이나 개선 사항이 있다면 자유롭게 작성해주세요.
      placeholder: 예) 네이밍이 명확하고 로직이 깔끔해요.

  - type: textarea
    id: questions
    attributes:
      label: 궁금한 점 또는 이해되지 않는 부분
      description: 코드 보면서 이해되지 않았던 부분이 있다면 작성해주세요.
      placeholder: 예) 이 부분 로직을 왜 이렇게 짜셨는지 궁금해요.
